

/*全局规则表*/
CREATE TABLE EACategory
	(
	ID             VARCHAR (50) NOT NULL, /*业务规则*/
	RNAME          VARCHAR (50),/*名称*/
	TmpTab         VARCHAR (50),/*临时表名*/
	ImprtType      CHAR (1) DEFAULT ('0'), /*导入类型 1 本地0 excel*/
	ImprtProc      VARCHAR (100),/*上传存储过程*/
	CancelProc     VARCHAR (100),/*取消上传存储过程*/
	LoadProc       VARCHAR (100),/*上传到中间表调用存储过程*/
	SwitchProc     VARCHAR (100),/*切换执行存储过程*/
	Note           VARCHAR (100),/*备注*/
	CreateUser     VARCHAR (50),
	CreateTime     VARCHAR (20),
	LastModifyUser VARCHAR (50),
	LastModifyTime VARCHAR (20),
	ImprtDLL       VARCHAR (100),/*扩展DLL 程序;类名称*/
	GetProc        VARCHAR (100),/*本地取数存储过程*/
	CONSTRAINT PK_EACATEGORY PRIMARY KEY (ID)
	)
GO

/*全局规则列信息*/
CREATE TABLE EACatCols
	(
	ID         VARCHAR (50) NOT NULL,/*列ID*/
	RID        VARCHAR (50),/*业务ID*/
	FCode      VARCHAR (50),/*字段编号*/
	FName      VARCHAR (50),/*字段名称*/
	FType      VARCHAR (50),/*字段类型 char varchar int date float*/
	IsShow     CHAR (1),/*是否显示*/
	FLength    int,/*长度*/
	FPrec      int,/*精度*/
	IsReadonly CHAR (1),/*是否只读*/
	HelpID     VARCHAR (50),/*帮助ID  EAHelp主键*/
	BindCol    VARCHAR (50),/*帮助绑定字段*/
	IsMatch    VARCHAR (50) DEFAULT ('0'), /*是否匹配*/
	MatchName  VARCHAR (200), /*四个字段记录匹配规则*/
	IsRequire  CHAR (1) DEFAULT ('0'),/*是否必填*/
	RCols      clob,/*返回字段*/
	SCols      clob,/*赋值字段*/
	SortOrder  int,/*列排序*/
	Width      VARCHAR (40),/*列宽度*/
	MatchRule  VARCHAR(200),/*关联字段 用于批量帮助更新*/
	HelpFilter varchar(500),/*帮助过滤*/
	IsSum      char(1) DEFAULT ('0'),/*是否合计*/
	CONSTRAINT PK_EACATCOLS PRIMARY KEY (ID)
	)
GO


/*单位规则表*/
CREATE TABLE EACmpCategory
	(
	ID             VARCHAR (50) NOT NULL,/*单位规则ID*/
	CID            VARCHAR (50),/*全局规则ID*/
	DWBH           VARCHAR (50),/*单位编号？*/
	BMBH           VARCHAR (50),/*部门编号？ 估计可以不用*/
	RNAME          VARCHAR (50),/*名称？*/
	TmpTab         VARCHAR (50),/*从全局表带过来*/
	ImprtType      VARCHAR (50),/*从全局表带过来*/
	ImprtProc      VARCHAR (100),/*从全局表带过来*/
	CancelProc     VARCHAR (100),/*从全局表带过来*/
	Note           VARCHAR (200),
	CreateUser     VARCHAR (50),
	CreateTime     VARCHAR (20),
	LastModifyUser VARCHAR (50),
	LastModifyTime VARCHAR (20),
	StartLine      VARCHAR (50),	/*Excel起始行*/
	IsREF          CHAR (1),		/*是否显示关联导入*/
	RefStart       INT,				/*关联表读取起始行*/
	RefProc        VARCHAR (50),	/*关联表上传调用存储过程*/
	RefRemoveProc  VARCHAR (50),	/*关联表移除调用存储过程*/
	IsCustom       CHAR (1),		/*是否显示自定义按钮*/
	CustomProc     VARCHAR (50),/*自定义点击执行存储过程*/
	CustomName     VARCHAR (50),/*自定义按钮名称*/
	CONSTRAINT PK_EACMPCATEGORY PRIMARY KEY (ID)
	)
GO
/*单位规则列信息*/
CREATE TABLE EACmpCateCols
	(
	ID           VARCHAR (50) NOT NULL, /*列ID*/
	RID          VARCHAR (50),/*单位规ID*/
	FCode        VARCHAR (50),/*字段编号 从全局列表带过来*/
	FName        VARCHAR (50),/*字段名称 从全局列表带过来*/
	MatchName    VARCHAR (50),/*对应excel标题*/
	DeafultValue VARCHAR (50),/*默认值*/
	CalcSQL      clob,/*计算sql （xx=‘1’）where 1=1 */
	SortOrder    int,/*列排序*/
	CONSTRAINT PK_EACMPCATECOLS PRIMARY KEY (ID)
	)
GO



/*左侧分类导航*/
CREATE TABLE EAFunc
	(
	Id       VARCHAR (50) NOT NULL,
	Code     VARCHAR (50),
	Name     VARCHAR (50),
	IsDetail CHAR (1) DEFAULT ('0'),/*是否明细*/
	PId      VARCHAR (50),
	REFID    VARCHAR (50),
	REFType  CHAR (1),    /*1、全局规则ID 2、url 3、winform*/
	URLInfo varchar(1000),/*超链接URL信息？*/
	FormInfo varchar(200),/*winform form dll*/
	CONSTRAINT PK_EAFUNC PRIMARY KEY (Id)
	)
GO

/*自定义帮助表*/
CREATE TABLE EAHelp
	(
	ID          VARCHAR (50) NOT NULL,/*帮助ID*/
	CODE        VARCHAR (50),/*编号 也就是表名称*/
	NAME        VARCHAR (50),/*帮助名称？*/
	SFields     VARCHAR (1000),/*取数字段？*/
	SFilter     VARCHAR (50),/*帮助过滤条件 and xx='' */
	HelpType    CHAR (1) DEFAULT ('0'),/*帮助类型 1 树形 0普通*/
	PathField   VARCHAR (50),/*分级码字段*/
	LevelField  VARCHAR (50),/*级数字段*/
	DetailField VARCHAR (50),/*是否明细字段*/
	IDField     VARCHAR (50),/*主键字段*/
	PIDField    VARCHAR (50),/*父ID字段*/
	GradeFormat VARCHAR (50),/*分级结构4444444*/
	ShowCols    VARCHAR (1000),/*显示列 格式 LSBZDW_DWBH,单位编号,200;LSBZDW_DWMC,单位名称,200  */
	PageSize    VARCHAR (50),/*分页大小*/
	CodeField   VARCHAR (50),/*帮助编号字段*/
	NameField   VARCHAR (50),/*帮助名称字段*/
	CONSTRAINT PK_EAHELP PRIMARY KEY (ID)
	)
GO

CREATE TABLE EAOpLog
	(
	ID       VARCHAR (50) NOT NULL,
	RID      VARCHAR (50),
	UserCode VARCHAR (50),
	OpInfo   clob,
	OpTime   VARCHAR (50),
	CONSTRAINT PK_EAOPLOG PRIMARY KEY (ID)
	)
GO

/*关联表*/
CREATE TABLE EARefTable
	(
	ID         VARCHAR (36) NOT NULL,
	UserId     VARCHAR (36),/*用户ID*/
	UserName   VARCHAR (36),/*用户名称*/
	YWID       VARCHAR (36),/*业务标识ID*/
	DWBH       VARCHAR (36),/*单位编号*/
	FLAG       CHAR (1),/*状态*/
	CreateTime VARCHAR (20),/*创建时间*/
	XM01       VARCHAR (255),
	XM02       VARCHAR (255),
	XM03       VARCHAR (255),
	XM04       VARCHAR (255),
	XM05       VARCHAR (255),
	XM06       VARCHAR (255),
	XM07       VARCHAR (255),
	XM08       VARCHAR (255),
	XM09       VARCHAR (255),
	XM10       VARCHAR (255),
	XM11       VARCHAR (255),
	XM12       VARCHAR (255),
	XM13       VARCHAR (255),
	XM14       VARCHAR (255),
	XM15       VARCHAR (255),
	XM16       VARCHAR (255),
	XM17       VARCHAR (255),
	XM18       VARCHAR (255),
	XM19       VARCHAR (255),
	XM20       VARCHAR (255),
	XM21       VARCHAR (255),
	XM22       VARCHAR (255),
	XM23       VARCHAR (255),
	XM24       VARCHAR (255),
	XM25       VARCHAR (255),
	XM26       VARCHAR (255),
	XM27       VARCHAR (255),
	XM28       VARCHAR (255),
	XM29       VARCHAR (255),
	XM30       VARCHAR (255),
	XM31       VARCHAR (255),
	XM32       VARCHAR (255),
	XM33       VARCHAR (255),
	XM34       VARCHAR (255),
	XM35       VARCHAR (255),
	XM36       VARCHAR (255),
	XM37       VARCHAR (255),
	XM38       VARCHAR (255),
	XM39       VARCHAR (255),
	XM40       VARCHAR (255),
	XM41       VARCHAR (255),
	XM42       VARCHAR (255),
	XM43       VARCHAR (255),
	XM44       VARCHAR (255),
	XM45       VARCHAR (255),
	XM46       VARCHAR (255),
	XM47       VARCHAR (255),
	XM48       VARCHAR (255),
	XM49       VARCHAR (255),
	XM50       VARCHAR (255),
	CONSTRAINT PK_EAREFTABLE PRIMARY KEY (ID)
	)
GO

/*测试用临时表*/
CREATE TABLE TMP_LSWLDW
	(
	ID         VARCHAR (50) NOT NULL,
	FLAG       CHAR (1) DEFAULT ('0'),/*默认有  0 待上传 1已上传 2处理中 必须有*/
	CreateUser VARCHAR (50),/*创建用户账号 必须有*/
	CreateTime VARCHAR (20),/*创建时间 必须有*/
	COLORZT    CHAR (1),/*颜色状态 必须有 1 黄色 3绿色 4红色*/
	DWBH       VARCHAR (50),/*导入单位信息 必须有*/
	YWID       VARCHAR (50),/*业务标识ID 全局规则ID？ 必须有*/
	DWMC       VARCHAR (50),
	NOTE       VARCHAR (1000),
	CONSTRAINT PK_TMP_LSWLDW PRIMARY KEY (ID)
	)
GO



CREATE TABLE TMP_LSWLDW1
	(
	ID         VARCHAR (50) NOT NULL,
	FLAG       CHAR (1) DEFAULT ('0'),
	DWBH       VARCHAR (50),
	DWMC       VARCHAR (50),
	NOTE       VARCHAR (1000),
	CreateUser VARCHAR (50),
	CreateTime VARCHAR (20),
	COLORZT    CHAR (1),
	CONSTRAINT PK_TMP_LSWLDW1 PRIMARY KEY (ID)
	)
GO




create table YZ_E_File_File 
( FileId  varchar2 (60) , FileName  varchar2 (60) , FilePath  varchar2 (60) , FileType  varchar2 (60) , AddTime DATE  DEFAULT sysdate)

create table  YZ_E_SDNOTICE_READ (READID VARCHAR2(60)  default   SYS_GUID() ,READNAME VARCHAR2(60),READTIME DATE default sysdate ,RComment VARCHAR2(4000))





/*多维分析建表语句*/

/*查询自定义字段*/

CREATE TABLE EACustomFields
	(
	ClassSetCode   VARCHAR (40) NOT NULL,
	ActTable       VARCHAR (50) NOT NULL,
	FieldName      VARCHAR (50) NOT NULL,
	DisplayName    VARCHAR (50),
	Note           VARCHAR (100),
	FieldType      CHAR (1) DEFAULT ('0') NOT NULL,
	InputType      CHAR (1) DEFAULT ('0') NOT NULL,
	IsDeleted      CHAR (1) DEFAULT ('0') NOT NULL,
	IsRequired     CHAR (1) DEFAULT ('0') NOT NULL,
	CharLength     INT DEFAULT ((0)) NOT NULL,
	MaxValue       DECIMAL (20, 8) DEFAULT ((0)) NOT NULL,
	MinValue       DECIMAL (20, 8) DEFAULT ((0)) NOT NULL,
	DecimalDigits  INT DEFAULT ((0)) NOT NULL,
	DateTimeFormat CHAR (1) DEFAULT ('0') NOT NULL,
	DefaultValue   VARCHAR (255),
	GetInfoFrom    VARCHAR (50),
	GetFiledType   CHAR (1),
	GetFieldType   CHAR (1),
	Formula        VARCHAR (255),
	IsUserCustom   CHAR (1) DEFAULT ('1') NOT NULL,
	IsDisplay      CHAR (1) DEFAULT ('1') NOT NULL,
	DisplayOrder   INT DEFAULT ((100)) NOT NULL,
	OrderFields    VARCHAR (1000),
	IfEdit         CHAR (1) DEFAULT ('1'),
	FormulaOrder   INT,
	ALIAS          VARCHAR (20),
	DSID           VARCHAR (30),
	GetInfoWhere   VARCHAR (300),
	GetOtherValue  VARCHAR (400),
	FieldColSpan   CHAR (1) DEFAULT ('1'),
	CONSTRAINT PK_EACUSTOMFIELDS PRIMARY KEY (ClassSetCode, ActTable, FieldName)
	)
GO

/*查询定义*/
CREATE TABLE JTPUBQRDEF
	(
	JTPUBQRDEF_ID      VARCHAR (40) NOT NULL,
	JTPUBQRDEF_BH      VARCHAR (40),
	JTPUBQRDEF_MC      VARCHAR (100),
	JTPUBQRDEF_TITLE   VARCHAR (100),
	JTPUBQRDEF_SUBTIL  VARCHAR (100),
	JTPUBQRDEF_TYPE    VARCHAR (10),
	JTPUBQRDEF_DBSRC   VARCHAR (50),
	JTPUBQRDEF_SQL     clob,
	JTPUBQRDEF_ORA    clob,
	JTPUBQRDEF_DWFIELD VARCHAR (400),
	JTPUBQRDEF_RQFIELD VARCHAR (40),
	JTPUBQRDEF_WHERE   VARCHAR (100),
	CONSTRAINT PK_JTPUBQRDEF PRIMARY KEY (JTPUBQRDEF_ID)
	)
GO




/*查询参数设置*/

CREATE TABLE JTPUBQRPARAMDEF
	(
	PARAMDEF_ID     VARCHAR (40) NOT NULL,
	PARAMDEF_QRYID  VARCHAR (40),
	PARAMDEF_ORD    VARCHAR (40),
	PARAMDEF_NAME   VARCHAR (100),
	PARAMDEF_TYPE   VARCHAR (10),
	PARAMDEF_CMP    VARCHAR (20),
	PARAMDEF_ISUSR  VARCHAR (1),
	PARAMDEF_CMPSTR VARCHAR (80),
	CONSTRAINT PK_JTPUBQRPARAMDEF PRIMARY KEY (PARAMDEF_ID)
	)
GO



/*联查设置*/

CREATE TABLE JTPUBLINKQRY
	(
	JTPUBLINKQRY_QRYID        VARCHAR (40) NOT NULL,
	JTPUBLINKQRY_CODE         VARCHAR (200) NOT NULL,
	JTPUBLINKQRY_NAME         VARCHAR (200),
	JTPUBLINKQRY_TYPE         VARCHAR (100),
	JTPUBLINKQRY_URL_PATH     VARCHAR (1000),
	JTPUBLINKQRY_CLASS        VARCHAR (1000),
	JTPUBLINKQRY_PARAMS       VARCHAR (1000),
	JTPUBLINKQRY_REPLACEVALUE VARCHAR (1000),
	CONSTRAINT PK_JTPUBLINKQRY PRIMARY KEY (JTPUBLINKQRY_QRYID, JTPUBLINKQRY_CODE)
	)
GO


/*多维分析定义*/
CREATE TABLE JTPUBQRYFAV
	(
	QRYFAV_QRYID     VARCHAR (40) NOT NULL,
	QRYFAV_HASH      VARCHAR (200) NOT NULL,
	QRYFAV_NAME      VARCHAR (200) NOT NULL,
	QRYFAV_LOCATION  VARCHAR (10),
	QRYFAV_CREATER   VARCHAR (40),
	QRYFAV_ROW       VARCHAR (2000),
	QRYFAV_COL       VARCHAR (2000),
	QRYFAV_DATA      VARCHAR (2000),
	QRYFAV_FILTER    VARCHAR (2000),
	QRYFAV_SEL       VARCHAR (2000),
	QRYFAV_DEFAULT   CHAR (1),
	QRYFAV_FILTERVAL VARCHAR (2000),
	CONSTRAINT PK_JTPUBQRYFAV PRIMARY KEY (QRYFAV_QRYID, QRYFAV_HASH, QRYFAV_NAME)
	)
GO


CREATE TABLE JTPUBQRYFAVFILTER
	(
	QRYFILTER_QRYID VARCHAR (40) NOT NULL,
	QRYFILTER_USER  VARCHAR (40) NOT NULL,
	QRYFILTER_HASH  VARCHAR (200) NOT NULL,
	QRYFILTER_NAME  VARCHAR (80) NOT NULL,
	QRYFILTER_FIELD VARCHAR (40) NOT NULL,
	QRYFILTER_VALUE VARCHAR (500) NOT NULL,
	CONSTRAINT PK_JTPUBQRYFAVFILTER PRIMARY KEY (QRYFILTER_QRYID, QRYFILTER_USER, QRYFILTER_HASH, QRYFILTER_NAME, QRYFILTER_FIELD, QRYFILTER_VALUE)
	)
GO





CREATE TABLE JTPUBQRYFAVVISIT
	(
	QRYFAVVISIT_QRYID  VARCHAR (40) NOT NULL,
	QRYFAVVISIT_HASH   VARCHAR (200) NOT NULL,
	QRYFAVVISIT_USER   VARCHAR (40) NOT NULL,
	QRYFAVVISIT_ROW    VARCHAR (1000),
	QRYFAVVISIT_COL    VARCHAR (1000),
	QRYFAVVISIT_DATA   VARCHAR (1000),
	QRYFAVVISIT_FILTER VARCHAR (1000),
	QRYFAVVISIT_SEL    VARCHAR (1000),
	CONSTRAINT PK_JTPUBQRYFAVVISIT PRIMARY KEY (QRYFAVVISIT_QRYID, QRYFAVVISIT_HASH, QRYFAVVISIT_USER)
	)
GO



CREATE TABLE EAOTGS
	(
	F_DWBH  VARCHAR (30) DEFAULT (' ') NOT NULL,
	F_ID    VARCHAR (60) NOT NULL,
	F_GSBH  VARCHAR (2) NOT NULL,
	F_OTBH  VARCHAR (2) NOT NULL,
	F_TEXT  VARCHAR (255) NOT NULL,
	F_OTBZ  VARCHAR (1) NOT NULL,
	F_JS    VARCHAR (1) NOT NULL,
	F_ALIGN VARCHAR (1) NOT NULL,
	CONSTRAINT PK_EAOTGS PRIMARY KEY (F_DWBH, F_ID, F_GSBH, F_OTBH)
	)
GO





CREATE TABLE EATIGS
	(
	F_DWBH     VARCHAR (30) DEFAULT (' ') NOT NULL,
	F_ID       VARCHAR (60) NOT NULL,
	F_GSBH     VARCHAR (2) NOT NULL,
	F_TIBH     VARCHAR (18) NOT NULL,
	F_JS       VARCHAR (1),
	F_FIELD    VARCHAR (50),
	F_TEXT     VARCHAR (255),
	F_TYPE     VARCHAR (1),
	F_ALIGN    VARCHAR (1),
	F_WIDTH    INT DEFAULT ((0)),
	F_PROP     VARCHAR (3),
	F_PREC     VARCHAR (20),
	F_DISP     VARCHAR (254),
	F_REAL     VARCHAR (254),
	F_HJBZ     VARCHAR (1) DEFAULT ('0'),
	F_PXBZ     VARCHAR (1) DEFAULT ('0'),
	F_YHBZ     VARCHAR (1) DEFAULT ('0'),
	F_FHBZ     VARCHAR (1) DEFAULT ('1'),
	F_HZBZ     VARCHAR (1) DEFAULT ('0'),
	F_COLOR    VARCHAR (700) DEFAULT (' '),
	F_FORMAT   VARCHAR (50),
	F_ISGD     VARCHAR (1),
	F_TSTEXT   VARCHAR (200),
	F_GROUP    VARCHAR (50),
	F_TSHID    VARCHAR (50),
	F_PSUMTYPE VARCHAR (10),
	CONSTRAINT PK_EATIGS PRIMARY KEY (F_DWBH, F_ID, F_GSBH, F_TIBH)
	)
GO



CREATE TABLE EATIGSDEVQRY
	(
	F_DWBH  VARCHAR (30) NOT NULL,
	F_ID    VARCHAR (60) NOT NULL,
	F_GSBH  VARCHAR (2) NOT NULL,
	F_TIBH  VARCHAR (18) NOT NULL,
	F_JS    VARCHAR (1),
	F_FIELD VARCHAR (30),
	F_TEXT  VARCHAR (30),
	F_TYPE  VARCHAR (1),
	F_ALIGN VARCHAR (1),
	F_WIDTH INT,
	F_PROP  VARCHAR (3),
	F_PREC  VARCHAR (20),
	F_DISP  VARCHAR (254),
	F_REAL  VARCHAR (254),
	F_HJBZ  VARCHAR (1),
	F_PXBZ  VARCHAR (1),
	F_YHBZ  VARCHAR (1),
	F_FHBZ  VARCHAR (1),
	F_HZBZ  VARCHAR (1),
	F_COLOR VARCHAR (700),
	CONSTRAINT PRI_EATIGSDEVQRY PRIMARY KEY (F_DWBH, F_ID, F_GSBH, F_TIBH)
	)
GO

CREATE TABLE EAZBGS
	(
	F_DWBH  VARCHAR (30) DEFAULT (' ') NOT NULL,
	F_ID    VARCHAR (60) NOT NULL,
	F_GSBH  VARCHAR (2) NOT NULL,
	F_GSMC  VARCHAR (30),
	F_CAPT  VARCHAR (255) NOT NULL,
	F_CAPH  INT DEFAULT ((0)) NOT NULL,
	F_SCAPH INT DEFAULT ((0)) NOT NULL,
	F_BTGD  INT DEFAULT ((0)) NOT NULL,
	F_ROWH  INT DEFAULT ((0)) NOT NULL,
	F_BWGD  INT DEFAULT ((0)) NOT NULL,
	F_SPACE INT DEFAULT ((0)) NOT NULL,
	F_SYBZ  CHAR (1) DEFAULT ('0'),
	CONSTRAINT PK_EAZBGS PRIMARY KEY (F_DWBH, F_ID, F_GSBH)
	)
GO



/*增加版本表 2019-07-18*/
CREATE TABLE dbo.EAVersion
	(
	ID      VARCHAR (50),
	VERSION VARCHAR (50)
	)
GO

